// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BADGE_cpp
List BADGE_cpp(arma::mat data, int anneal_iters, double T, int max_iter, double tol_relative, double tol_s, arma::umat is_na, bool normalize_data, bool is_nonzero_mean);
RcppExport SEXP _BADGE_BADGE_cpp(SEXP dataSEXP, SEXP anneal_itersSEXP, SEXP TSEXP, SEXP max_iterSEXP, SEXP tol_relativeSEXP, SEXP tol_sSEXP, SEXP is_naSEXP, SEXP normalize_dataSEXP, SEXP is_nonzero_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type anneal_iters(anneal_itersSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_relative(tol_relativeSEXP);
    Rcpp::traits::input_parameter< double >::type tol_s(tol_sSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type is_na(is_naSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize_data(normalize_dataSEXP);
    Rcpp::traits::input_parameter< bool >::type is_nonzero_mean(is_nonzero_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(BADGE_cpp(data, anneal_iters, T, max_iter, tol_relative, tol_s, is_na, normalize_data, is_nonzero_mean));
    return rcpp_result_gen;
END_RCPP
}
