# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BADGE_cpp <- function(data, anneal_iters, T, max_iter, tol_relative, tol_s, is_na, normalize_data, is_nonzero_mean) {
    .Call(`_BADGE_BADGE_cpp`, data, anneal_iters, T, max_iter, tol_relative, tol_s, is_na, normalize_data, is_nonzero_mean)
}

